### PR TITLE
Update backup.md

### PR DESCRIPTION
**Pull request by Alexhqolma**
Added Nakivo as one more example of popular backup solutions

> Before submitting the pull request, you must agree with the following statements by checking both boxes with a 'x'.
> * [ ] "I accept that my contribution is placed under the CC BY-SA 2.0 license [1]."
> * [ ] "My contribution complies with the Developer Certificate of Origin [2]." 
>
> [1] https://creativecommons.org/licenses/by-sa/2.0/
> [2] https://docs.xcp-ng.org/project/contributing/#developer-certificate-of-origin-dco

### CODE REVIEW

**Comment by olivierlambert** [comment]
Hi @Alexhqolma are you from Nakivo or related to this company?

**Comment by Alexhqolma** [comment]
Hi,

My partner, Mariia Lvovych, is the outreach manager at Nakivo. She asked me to help edit your page.

I would appreciate it if you could include NAKIVO on your list of popular backup solutions. It is also featured as one of the leaders in data backup on https://www.getapp.com/security-software/backup/category-leaders/.

**Comment by Alexhqolma** [comment]
Hi,

I recommended NAKIVO as an alternative popular backup solution because I am using it to back up data within a virtualized environment. It is also recognized as a leader in the data backup category on GetApp.com: https://www.getapp.com/security-software/backup/category-leaders/.

**Comment by Alexhqolma** [comment]
Please contact mariia.lvovych@nakivo.com for more details.

**Comment by olivierlambert** [comment]
Will do, thanks!

**Comment by olivierlambert** [comment]
Merged via my own contribution, closing here :)

**Pull request closed without merging**
