### PR TITLE
Add persistent DNS search domains

### PR DESCRIPTION
**Pull request by Forza-tng**
Signed-off-by: Forza <68693597+Forza-tng@users.noreply.github.com>

> Before submitting the pull request, you must agree with the following statements by checking both boxes with a 'x'.
> * [X] "I accept that my contribution is placed under the CC BY-SA 2.0 license [1]."
> * [X] "My contribution complies with the Developer Certificate of Origin [2]." 
>
> [1] https://creativecommons.org/licenses/by-sa/2.0/
> [2] https://xcp-ng.org/docs/contributing.html#developer-certificate-of-origin-dco

### CODE REVIEW

**Review by Forza-tng — COMMENTED** [review]
Signed-off-by: Forza <68693597+Forza-tng@users.noreply.github.com>

**Comment by stormi** [comment]
Looked good. Why close it?

**Comment by stormi** [comment]
I see, the check failed because your e-mail is marked private in github, and you sign-off did not match. You should check your github e-mail parameters and retry.

**Comment by Forza-tng** [comment]
I'll leave this for now. If you want to add the information, it is good, otherwise I'll leave the suggestion as is for now.

**Comment by Forza-tng** [comment]
Perhaps you or someone at Vates can add it instead?

**Comment by stormi** [comment]
Technically, I can, and very easily. But I'm not supposed to write sign-offs for contributers. It would be like there's no sign-off at all as I would be the one adding it.

**Comment by stormi** [comment]
I'll do it, and we can always point a this discussion to assess that you asked me to :shrug:

**Comment by stormi** [comment]
Done: https://github.com/xcp-ng/xcp-ng-org/commit/3a8697d2e8c0c1e38a1845bd297735193db2f519

Thanks for this contribution.

**Pull request closed without merging**
