### PR TITLE
Update vms.md

### PR DESCRIPTION
**Pull request by M0nty99**
Fixed link for the Windows guest tools

> Before submitting the pull request, you must agree with the following statements by checking both boxes with a 'x'.
> * [x] "I accept that my contribution is placed under the CC BY-SA 2.0 license [1]."
> * [x] "My contribution complies with the Developer Certificate of Origin [2]." 
>
> [1] https://creativecommons.org/licenses/by-sa/2.0/
> [2] https://docs.xcp-ng.org/project/contributing/#developer-certificate-of-origin-dco

### CODE REVIEW

**Review by olivierlambert — APPROVED** [review]

**Comment by olivierlambert** [comment]
Thanks for your contrib, we'll merge it ASAP!

**Comment by stormi** [comment]
The new download link is for tools built for XenServer 8 Preview. Maybe they are good for 8.2 too, but we haven't tested it thoroughly. The previous link is still valid for version 8.2.

**Comment by M0nty99** [comment]
> The new download link is for tools built for XenServer 8 Preview. Maybe they are good for 8.2 too, but we haven't tested it thoroughly. The previous link is still valid for version 8.2.

The older link is not functional if you don't have an account, and Citrix doesn't allow (anymore) to create an account with a license for Citrix. 
I'm running the tools now on Windows server 2022 (haven't tested Linux yet) and seem to be working fine.

**Review by stormi — APPROVED** [review]
We can change to this link for now and see how it evolves in the future.

**Comment by olivierlambert** [comment]
Rebuild is done and the change is now visible: https://docs.xcp-ng.org/vms/#management-agent--device-drivers

**Pull request merged**
