### PR TITLE
improved "Root password" description

### PR DESCRIPTION
**Pull request by dredknight**
added hash type requirement
how to create hash example

> Before submitting the pull request, you must agree with the following statements by checking both boxes with a 'x'.
> * [x] "I accept that my contribution is placed under the CC BY-SA 2.0 license [1]."
> * [x] "My contribution complies with the Developer Certificate of Origin [2]." 
>
> [1] https://creativecommons.org/licenses/by-sa/2.0/
> [2] https://xcp-ng.org/docs/contributing.html#developer-certificate-of-origin-dco

Signed-off-by: dredknight

### CODE REVIEW

**Comment by olivierlambert** [comment]
You need to sign with your email in which you have this Github account.

> To avoid having PRs blocked in the future, always include Signed-off-by: Author Name <authoremail@example.com> in every commit message. You can also do this automatically by using the -s flag (i.e., git commit -s).

**Comment by dredknight** [comment]
Thanks Oliver,

I do commited those from the GUI so I am not sure how to edit and fix it. Will it work if i add this here.
Signed-off-by: Jordan Kostov jordankostow@gmail.com

**Comment by dredknight** [comment]
@olivierlambert  I made a new pull request that obliges the practice.

Forgive me for the spam :(

**Comment by stormi** [comment]
There may soon be a way to sign off more easily through github's interface. I'll ask for the beta feature to be activated so that we can try it.

**Pull request closed without merging**
