### PR TITLE
Add a guide about host reboot or shutdown

### PR DESCRIPTION
**Pull request by stormi**
Signed-off-by: Samuel Verschelde <stormi-xcp@ylix.fr>

Here's what it will look like
image

### CODE REVIEW

**Comment by olivierlambert** [comment]
You can disable a host via XO too.

**Comment by stormi** [comment]
I haven't found a way to disable it without triggering a host evacuate. Where is it?

**Comment by stormi** [comment]
I read in XO docs that maintenance mode is automatically existed at host startup. Currently testing is when host-disable was done from CLI to update the PR.

**Comment by olivierlambert** [comment]
We should probably keep disable option in XO if it makes sense then. Let us know what you think.

**Comment by stormi** [comment]
> We should probably keep disable option in XO if it makes sense then. Let us know what you think.

I think it could make sense for users who rely on local storage for their VMs, have VMs with PCI pass-through, or want to manually select where their move their VMs to.

**Comment by stormi** [comment]
Done: https://github.com/vatesfr/xen-orchestra/issues/5915

Can we merge?

**Comment by olivierlambert** [comment]
LGTM

**Pull request merged**
