### PR TITLE
NIC Renaming missing steps

### PR DESCRIPTION
**Pull request by dsiminiuk**
Removing the old PIFs, enabling the new NICS and re-introducing the pifs were missing steps.

### CODE REVIEW

**Comment by dsiminiuk** [comment]
@olivierlambert I think I've done what you asked but I'm a noob at this. Let me know if I need to take further action.

**Comment by olivierlambert** [comment]
Don't worry, someone will review it. Thanks a lot for your contribution! :+1:

**Comment by Fohdeesha** [comment]
Thanks for contributing! I made a couple small edits (directly to your source branch) to correct a typo and to better fit it into the grammatical style of the rest of the section. It looks good to be merged to me but I think @stormi has the final say :)

**Review by stormi — APPROVED** [review]
Looks good to me too

**Pull request merged**
